### ISSUE TITLE
[New Feature]: Use stage EFS as data temporary location for CHIRP execution

### ISSUE THREAD

**Issue by LucaCinquini** [unity-sds/unity-sps-prototype#227]
I believe we are now always mounting an EFS partition as /stage to all Verdi containers. To enable large data processing when executing the CHIRP workflow, we need to add this option when executing cwl-runner in the CWL Docker container:

--tmpdir-prefix /stage/ 

(note the trailing "/" as well)

**Comment by ryanhunter-jpl** [comment]
Option flag added and committed to [run_cwl_workflow.sh](https://github.com/unity-sds/unity-sps-register_job/blob/40168a17f2ad97bdc4c4086ac343593287396357/run_cwl_workflow.sh#L10).

In order to access `/stage` from the pge container I also had to add `/stage/` to the list of imported files when we build the hysds job-spec. That change can be seen [here](https://github.com/unity-sds/ades_wpst/blob/d68eeab0f259d841d917967625bbcdf3bd81b9ca/flask_ades_wpst/ades_hysds.py#L95).

The wps-t change has been built and pushed to ghcr.io/unity-sds/unity-sps-prototype/ades-wpst-api:develop 
The run_cwl_workflow.sh has been built and pushed in ghcr.io/unity-sds/unity-sps-prototype/sps-hysds-pge-base:develop

**Comment by LucaCinquini** [comment]
Thanks Ryan, since the tests on MCP-Dev succeeded the new flag should be working, closing.
